### ISSUE TITLE
Create Front End Login Page

### ISSUE THREAD

**Issue by bensoer** [iRAMBI/BCITBlurbBoard#1]
<b>For Task Completion</b>
- Implement Login UI Design from Invisionapp
- Implement Client Side Validation of Login Credentials
- Implement Forwarding to main page upon login

**Comment by ikhangura** [comment]
Finished design ... need to add  color + font scheme

**Comment by bensoer** [comment]
@ikhangura  - we made a couple changes and there are some issues with the branch.

**Comment by bensoer** [comment]
@ikhangura - Create a fork of the project. Clone the project and reintegrate the Login page in the dev branch.
