### ISSUE TITLE
Design and Implement HttpClient Class

### ISSUE THREAD

**Issue by bensoer** [iRAMBI/BCITBlurbBoard#16]
Get, Post, Put, Delete Class

**Comment by TheRocktopus** [comment]
Designed. Nearly complete. Breaking Alamofire out into a nice HTTP wrapper class proved to be more difficult than we expected (It's not built for that). I've requested a pull with what I have done so far - Alamofire integrated, HTTPClient test methods, example Get and Pull methods. Best to integrate Alamofire calls directly into your code for now.
