### ISSUE TITLE
iOS - Implement News Page

### ISSUE THREAD

**Issue by bensoer** [iRAMBI/BCITBlurbBoard#33]

**Comment by TheRocktopus** [comment]
Table cell for single news item button/preview has been prototyped. I can grab news items from the API, just writing methods to push the various elements into the cells.

Currently on pause to focus on midterms.

**Comment by bensoer** [comment]
@bensoer. Seed database with multiple news articles and comments

**Comment by TheRocktopus** [comment]
News page complete aside for minor alignment tweaks. Integrated with Single Article page.
