### ISSUE TITLE
Research iOS standards for layout

### ISSUE THREAD

**Issue by bensoer** [iRAMBI/BCITBlurbBoard#4]
<b> Tasks To Complete </b>
- Find layout standards for where items are located eg. Settings are kept in Apple General Settings ??
- What kind of menu options are there ?
- Apple Style Guide ?

**Comment by ryansadio** [comment]
**Official design guide**
[Designing for iOS](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/)

**Inspiration and resources**
[News article sample](https://designcode.io/xcode)
[iOS icons](http://icons8.com/web-app/for/ios7/message)
[iOS 8 GUI for Sketch](http://www.teehanlax.com/tools/iphone-sketch-app/)
[LinkedIn GUI for Sketch](http://www.sketchappsources.com/free-source/969-linkedin-gui-sketch-freebie-resource.html)
