### ISSUE TITLE
Research and Design Database Layout

### ISSUE THREAD

**Issue by bensoer** [iRAMBI/BCITBlurbBoard#5]
Formalize design and layout of the database

**Comment by TheRocktopus** [comment]
Design mostly done, still need to complete Visio document. Will be done TODAY! (Wednesday, January 21)

**Comment by TheRocktopus** [comment]
Design complete, diagram in OneNote

**Comment by TheRocktopus** [comment]
NEED TO ADD:
- programid to news
- coursesectionid to news
- expirydate
- faculty table! use mockup to fill

REMOVE:
- userid from course
- remove linkage between user and course
- attribute name from usercoursesection (replace with role)
