### ISSUE TITLE
Research API options

### ISSUE THREAD

**Issue by bensoer** [iRAMBI/BCITBlurbBoard#7]
Tentatively using ASP.NET for API use (being in C#)

Look up other options (Nodejs ? competitors ?)

Look up how to use ASP as an API ?

How will ASP interact with MySQL database ? How will it work with Push ?

**Comment by bensoer** [comment]
Created a comparison chart on OneNote here : https://onedrive.live.com/edit.aspx?cid=c70080a72ea4e115&id=documents&resid=C70080A72EA4E115!34119&app=OneNote&authkey=!AOncOpH9A_IqloA&&wd=target%28%2F%2FDesign.one%7Cf7dfcbf6-855e-41ea-8ed6-facff9a590d6%2FAPI%20Framework%20Pros%5C%2FCons%7C5e83f5a4-436a-41ad-8b84-0d290bd0155e%2F%29

**Comment by ryansadio** [comment]
Using ASP with MSSQL server on Azure
